`define L1D_CACHELINE_I  2'b00
`define L1D_CACHELINE_UC 2'b11
`define L1D_CACHELINE_UD 2'b10
`define L1D_CACHELINE_SC 2'b01

`define REFILL_MASTER_LOAD 0
`define REFILL_MASTER_TLB 1
`define REFILL_MASTER_STB 2

`define REFILL_AR_ID 1
 
`define AC_OPCODE_WIDTH 5
